spring:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: communication-service
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5434}/communication
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
server:
  port: ${SERVER_HTTP_PORT:8081}

service:
  hash-service:
    url: http://localhost:8082
