spring:
  application:
    name: hash-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}
  datasource:
    profile:
      username: ${DATABASE_USER:postgres}
      password: ${DATABASE_PASSWORD:postgres}
      jdbc-url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/hash
      driver-class-name: org.postgresql.Driver
server:
  port: ${SERVER_HTTP_PORT:8082}